### ISSUE TITLE
Brand new ✨ Python Pune logo

### ISSUE THREAD

**Issue by akshaygin** [pythonpune/design#1]
We do have Python Pune group active for years now. We should have logo that represents our identity for online profile and in the events that we organize.

Few things that need to take take when designing new logo:
1. Font that are going to use in the logo should have free and open source license, if you are using any available font.
2. Logo should have clear logomark and logotype or both combined.

Submit your mock-ups and templates here in this ticket, also comment out you feedback and suggestion.

Some Guidelines:
https://www.python.org/psf/trademarks/

**Comment by akshaygin** [comment]
Few designs that I am playing around:
![sticker](https://user-images.githubusercontent.com/16691314/55852501-ec4b3400-5b7a-11e9-98ee-5e5f506d1486.png)

![sticker4](https://user-images.githubusercontent.com/16691314/55852520-f836f600-5b7a-11e9-9f4b-ec6220b1c277.png)

![test](https://user-images.githubusercontent.com/16691314/55852548-143a9780-5b7b-11e9-97a6-0630d3651c23.png)

**Comment by chkumar246** [comment]
Thanks @akshay196 for working on this. It looks really nice.
Comments from #dgplug channel
```
12:05:02   @jasonbraganza ╡ chandankumar i love all of them. 3rd one is the keeper if the colours can be made more vibrant         │
12:06:45            sayan ╡ I don't know if 1st one fits the guidelines                                                            │
12:08:11                ⤷ ╡ and as jasonbraganza 3rd one needs more vibrant colors                                                 │
12:08:24                ⤷ ╡ my vote goes to 3rd with more vibrant colors                                                           │
12:08:25            @mbuf ╡ chandankumar, is it commercial?                                                                        │
12:09:11    @chandankumar ╡ mbuf: Nope                                                                                             │
12:09:22                ⤷ ╡ mbuf: it is going to be for python pune community.                                                     │
12:09:54                ⤷ ╡ And it is designed by akshay196 and vishal.                                                            │
12:10:36                ⚡ ╡ mbuf Today is training day. Expect late replies.                                                      │
12:11:06            @mbuf ╡ chandankumar, use a font with SIL Open Font License                                                    │

```

**Comment by pnemade** [comment]
I am not sure if we can get few more design options but If I need to choose I will go with 3rd option.

**Comment by akshaygin** [comment]
I am planning to design few more. I will showcase here once it reaches to the mark. Also I will try to change 3rd design with some vibrant colour as many people liked it.

Currently I am just posting my designs to get some suggestion, improvements from all.

**Comment by akshaygin** [comment]
Some designs I previously tried, just adding:
![sticker](https://user-images.githubusercontent.com/16691314/55978741-2a954000-5cae-11e9-9c11-976a00b8aeb4.png)

![des6](https://user-images.githubusercontent.com/16691314/55978759-36810200-5cae-11e9-93a0-ca15f3397780.png)

**Comment by akshaygin** [comment]
![pypune_logo_present_compact](https://user-images.githubusercontent.com/16691314/57056986-86f2ea80-6cc3-11e9-876d-8052e4a296fc.png)

**Comment by bhavin192** [comment]
@akshay196 can you please post above logo with some plain background?

**Comment by raukadah** [comment]
@SaptakS @aavrug Please have a look at the logo and help us in finalizing one.

**Comment by akshaygin** [comment]
Taking last logo into consideration, I have few idea of texture/colour and font combination:
![present1](https://user-images.githubusercontent.com/16691314/63495070-c2b4f880-c4dc-11e9-9e4d-0cc8834db537.png)

**Comment by adtandale** [comment]
The last image from the second row looks good to me with a white T-shirt and cap.

**Comment by pratikgadiya12** [comment]
I liked the logo @akshay196 
![image](https://user-images.githubusercontent.com/14973429/63915132-d5867a80-ca52-11e9-9b0f-c1dfc554d3e6.png)
however, would like to remove what's highlighted in orange in below image
![image](https://user-images.githubusercontent.com/14973429/63915067-acfe8080-ca52-11e9-9023-02a6831fe321.png)

**Comment by bhavin192** [comment]
@akshay196 will be really awesome if you can create a PR with final logo in SVG or some other editable format. Let's make the change at all places once you add the logo to this repository.

**Comment by bhavin192** [comment]
> @akshay196 will be really awesome if you can create a PR with final logo in SVG or some other editable format. Let's make the change at all places once you add the logo to this repository.

Hey @akshay196, do you have any update on this?

**Comment by akshaygin** [comment]
@bhavin192 Sorry for late reply. I will send PR with final logo.
