### ISSUE TITLE
Landing page of PythonPune

### ISSUE THREAD

**Issue by akshaygin** [pythonpune/design#2]
Design and develop a webpage where people get to know about ourself. Feel free to share your idea here.

**Comment by akshaygin** [comment]
This task in under progress. There are some action items after discussion with @bhavin192 :

- [x] Create two repos: content and theme.
- [x] Finalize text content on the site.
- [x] The meetup page summary should be the posts on the hugo site.
- [x] Disable "Previous meeting" section from the page when posts are added.
- [ ] Brainstorming on showing weekly newsletter on the site with RSS feed (future scope).
- [ ] ~Brainstorming on showing events/activities on the page. (Not recommended now)~

**Comment by akshaygin** [comment]
We need content on the landing page at the place where "Lorem ipsum dolor sit ame..." is written below:
![Screenshot from 2020-06-09 15-23-47](https://user-images.githubusercontent.com/16691314/84134093-9b152980-aa37-11ea-8764-9230d933a9ec.png)
![Screenshot from 2020-06-09 15-24-00](https://user-images.githubusercontent.com/16691314/84134100-9d778380-aa37-11ea-8199-6fd009885aba.png)

**Comment by akshaygin** [comment]
Update: Started converting [meetup-talks](https://github.com/pythonpune/meetup-talks/) repository into hugo site. The progress can be seen [here](https://github.com/akshay196/meetup-talks/tree/hugo-site)

**Comment by Pradhvan** [comment]
@akshay196 I can help with content. 😄 Will share a commen google doc soon. 

> the text content on the site.

**Comment by Pradhvan** [comment]
@bhavin192  @akshay196  Just sharing the link here(_It's 50% done_) feel free to look at it and comment. [Google doc link](https://docs.google.com/document/d/1Y6zxoGmQZodUUGAyvX4UIIRf4wiXKKqZ-b-asiuIfJY/edit?usp=sharing)

**Comment by akshaygin** [comment]
Submitted PR to add text content on the homepage: https://github.com/pythonpune/meetup-talks/pull/117 
@Pradhvan @bhavin192 Please review.

**Comment by akshaygin** [comment]
Closing this issue as we done with initial version of site. Thanks @bhavin192 @Pradhvan and others for your support.
