### ISSUE TITLE
Design banners for the virtual meetups

### ISSUE THREAD

**Issue by akshaygin** [pythonpune/design#5]
Since this COVID situation, we are arranging virtual meetups. It would be nice to have few banners ready for the virtual events to showcase. For examples:
 - Thank you banner (Ref: https://youtu.be/y6W480Y_KbU?t=6416)
 - Welcome banner (Ref: https://youtu.be/y6W480Y_KbU?t=33)

**Comment by akshaygin** [comment]
looping @bhavin192 @vishal-vvr @raukadah

**Comment by akshaygin** [comment]
Welcome banner image: (1912X1080 px)
![welcome_banner](https://user-images.githubusercontent.com/16691314/108750552-1290d780-7539-11eb-8bb8-669bafb7776b.png)

Thank you banner image: (1912X1080 px)
![thankyou_banner](https://user-images.githubusercontent.com/16691314/108750588-1de40300-7539-11eb-9fb1-fe961d7251b1.png)

**Comment by akshaygin** [comment]
@bhavin192 Please take a look in the content.

**Comment by vishalvvr** [comment]
@akshay196, banner images looks good. 
Just one thought, should we also include our [youtube channel](https://www.youtube.com/c/PythonPune) name/link ?
eg: "View all our past meetup videos on youtube channel"   
or 
once we complete this [issue](https://github.com/pythonpune/meetup-talks/issues/143), add link to [https://pyvideo.org](https://pyvideo.org/events.html)

**Comment by bhavin192** [comment]
Images look simple and nice.
Few points,
- We need to include website link (should be fine to skip GitHub link in that case).
- Instead of adding a link to YouTube, we can add something like this:
  ```
  Submit a talk, get event summaries, recordings, and newsletters
    pythonpune.in
  ``` 
  That way, if we plan to change the video host (something else than YouTube), the website will remain a source of truth.

**Comment by akshaygin** [comment]
![thankyou_banner_2](https://user-images.githubusercontent.com/16691314/108907706-54de1580-761a-11eb-904e-4f440a1e93c1.png)

Hope this cover all.

**Comment by bhavin192** [comment]
@akshay196 I have created cfp.pythonpune.in we can use it for first point.
Also, should it be: Join the Telegram group?

**Comment by akshaygin** [comment]
![thankyou_banner_3](https://user-images.githubusercontent.com/16691314/109045687-c9bd5800-76cb-11eb-8aa5-70de13fef466.png)

**Comment by akshaygin** [comment]
Final banner after fixing grammar:
![welcome_banner_4](https://user-images.githubusercontent.com/16691314/110664690-8a106900-81bf-11eb-86d5-f6554a48477a.png)

![thankyou_banner_4](https://user-images.githubusercontent.com/16691314/110664848-add3af00-81bf-11eb-8685-c974d0e93a81.png)

**Comment by bhavin192** [comment]
@akshay196 It would help if you can add these banners to the repository under banner folder. I would also consider adding source files (the original from GIMP or Inkscape files would do too). That way anyone can modify it.

**Comment by akshaygin** [comment]
@bhavin192 Added banner images and its source file at https://github.com/pythonpune/design/tree/master/banner 

The single source file includes both images source.
